json.user @user.username
json.email @profile.email
json.profile_picture @user.profile_picture
json.email @profile.email
json.pins @user.pins
json.boards @user.boards
json.followers @followed
json.followed @following
json.currentUserId @current_user.id
